apiVersion: v1
kind: Secret
metadata:
  name: {{ include "realsense-pose.fullname" . }}-secrets
  labels:
    {{- include "realsense-pose.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.auth.rootPassword }}
  mongo-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  {{- else }}
  {{- fail "mongodb.auth.rootPassword is required" }}
  {{- end }}
  {{- if .Values.api.auth.clientSecrets }}
  auth-client-secrets: {{ .Values.api.auth.clientSecrets | b64enc | quote }}
  {{- end }}
